# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('population', models.CharField(max_length=1000)),
                ('density', models.CharField(max_length=1000)),
                ('literacy', models.CharField(max_length=1000)),
            ],
        ),
    ]
